### ISSUE TITLE
I think your thing broke in Firefox 35 (now in Aurora)

### ISSUE THREAD

**Issue by joallard** [bigwave/livereload-extensions#1]
Just updated, and poof! can't make it work.

**Comment by bigwave** [comment]
Hi,

Could you try the following and see if it works for you?
https://addons.mozilla.org/en-US/firefox/addon/remotelivereload/versions/0.0.6

Cheers

**Comment by joallard** [comment]
Fix confirmed in Aurora 36. Thanks!

**Comment by joallard** [comment]
Actually, it now seems broken in Aurora 36.
