### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by khaled** [bigwave/livereload-extensions#5]
Currently the ws:// protocol is used if the hosting page is https.  This is forbidden, at least in chrome - wss must be used instead.  I'm guessing this'd be a pretty easy fix; see https://github.com/mklabs/tiny-lr/commit/f97eaa57a70287dda8843e1d7aaa2ad2f577ecf9 for an example.

**Comment by bigwave** [comment]
I've just published version 0.0.46 on the chrome web store, it should appear sometime in the next hour, could you try it and see if it works for you?

**Comment by khaled** [comment]
Works beautifully - thank you!!!
